### ISSUE TITLE
locks() returns both device types

### ISSUE THREAD

**Issue by thomkaufmann** [pschmitt/pynuki#48]
The problem seems to be in _get_devices() where the condition on self.list(device_type=device_type) is ignored when device_type is 0. 
It works properly for openers(), returning just devices of device_type 2.

**Comment by pschmitt** [comment]
Ah! Right this is due to the following check:
https://github.com/pschmitt/pynuki/blob/b3dd441a7dae74a392f91e80f53e196ea3c06bc9/pynuki/bridge.py#L128

This prints out "nope" twice:

```python
varNone = None
var0 = 0

if varNone:
  print("varNone passed the test")
else:
  print("nope")

if var0:
  print("var0 passed the test")
else:
  print("nope")
```

The test should be `ìf device_type is not None`.

Will fix asap. Thanks!
