### ISSUE TITLE
AssertionError: Failed to update data for lock. Nuki ID None volatized.

### ISSUE THREAD

**Issue by thomkaufmann** [pschmitt/pynuki#54]
Hi @pschmitt, I'm seeing these errors in my HA logs, and the lock is no longer available in HA until I restart the HA server. The opener continues to work just fine. 

This is with pynuki 1.3.7 and homeassistant-0.110.1.

Thanks! 

> may 22 00:33:24 hass hass[170685]: 2020-05-22 00:33:24 INFO (SyncWorker_2) [pynetgear] Get attached devices
may 22 00:33:35 hass hass[170685]: 2020-05-22 00:33:35 INFO (SyncWorker_3) [pynetgear] Get attached devices
may 22 00:33:46 hass hass[170685]: 2020-05-22 00:33:46 INFO (SyncWorker_3) [pynetgear] Get attached devices
may 22 00:33:48 hass hass[170685]: 2020-05-22 00:33:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for lock.hodor fails
may 22 00:33:48 hass hass[170685]: Traceback (most recent call last):
may 22 00:33:48 hass hass[170685]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
may 22 00:33:48 hass hass[170685]:     await self.async_device_update()
may 22 00:33:48 hass hass[170685]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 472, in async_device_update
may 22 00:33:48 hass hass[170685]:     await self.hass.async_add_executor_job(self.update)
may 22 00:33:48 hass hass[170685]:   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
may 22 00:33:48 hass hass[170685]:     result = self.fn(*self.args, **self.kwargs)
may 22 00:33:48 hass hass[170685]:   File "/home/homeassistant/.homeassistant/custom_components/nuki/lock.py", line 124, in update
may 22 00:33:48 hass hass[170685]:     self._nuki_device.update(aggressive=level)
may 22 00:33:48 hass hass[170685]:   File "/srv/homeassistant/lib/python3.8/site-packages/pynuki/device.py", line 89, in update
may 22 00:33:48 hass hass[170685]:     assert data, (
may 22 00:33:48 hass hass[170685]: AssertionError: Failed to update data for lock. Nuki ID None volatized.

**Comment by thomkaufmann** [comment]
It happens when pynetgear attempts to get attached devices.

**Comment by pschmitt** [comment]
I don't know how to prevent that from happening, not at the pynuki level. To me that seems like a pynetgear/home assistant issue 🤷‍♂️

**Comment by thomkaufmann** [comment]
You're right. The [HA device tracker documentation](https://www.home-assistant.io/integrations/device_tracker/) doesn't describe the "devices" and "exclude" options which allow you whitelist/blacklist devices. If anyone else encounters this, visit the [Netgear integration documentation](https://www.home-assistant.io/integrations/netgear/) instead.
