### ISSUE TITLE
Bridge seems to not support "secure" tokens

### ISSUE THREAD

**Issue by bhuebschen** [pschmitt/pynuki#82]
I have a Nuki-Lock and a Nuki-Bridge connected to Home Assistant.

```
{
   "bridgeType":1,
   "ids":{
      "hardwareId": ####,
      "serverId": ####
   },
   "versions":{
      "firmwareVersion":"2.14.0",
      "wifiFirmwareVersion":"2.3.0"
   },
   "uptime":43432,
   "currentTime":"2022-07-30T06:35:40+00:00",
   "wlanConnected":true,
   "serverConnected":true,
   "scanResults":[
      {
         "deviceType":4,
         "nukiId": ####,
         "name":"Nuki_####",
         "rssi":-50,
         "paired":true
      }
   ]
}
```

But at some time, pynuki wasnt able to call the api due to an invalid token... after some investigation i found out, that the line:
https://github.com/pschmitt/pynuki/blob/22433b35ecc15422e756cc06c2489c9e4e8ab5c3/pynuki/bridge.py#L94
causes the error ... using the plaintext-token as in
https://github.com/pschmitt/pynuki/blob/22433b35ecc15422e756cc06c2489c9e4e8ab5c3/pynuki/bridge.py#L96
works fine.

Unfortunately i cannot disable "secure"-tokens via Home Assistant.. but on the other hand it would be fine if i know why hased tokens don't work on my setup (and how i can fix that)... now everytime pynuki get's updated, i need to "patch" it to get my setup work again.

Thanks in advance,
Benedikt

**Comment by bhuebschen** [comment]
Ich habe aktualisiere normalerweise immer alle firmware's recht zeitnah ... es dürfte also nicht an einer alten Version liegen

**Comment by phm46** [comment]
I have this issue for a long time. In my case it was caused because of wrong date/time on nuki bridge (few hours difference). That's why hash token fails and why I needed to use plaintext token.

**Comment by bhuebschen** [comment]
i checked date and time.. everything is fine.. but my bridge still dont want to accept the hashed token
